import { Review } from '../types/Review';

export const sampleReviews: Review[] = [
  {
    id: '1',
    type: 'cinema',
    title: 'Dune: Part Two',
    director: 'Denis Villeneuve',
    year: 2024,
    genre: 'Sci-Fi',
    rating: 5,
    reviewText: 'Villeneuve has crafted a masterpiece that honors Frank Herbert\'s vision while creating something uniquely cinematic. The visual spectacle is breathtaking, from the sweeping desert landscapes to the intricate production design. Timothée Chalamet delivers a powerful performance as Paul Atreides, capturing both his vulnerability and growing messianic presence. The film\'s exploration of power, destiny, and the cost of prophecy feels especially relevant today.',
    dateReviewed: '2024-03-15T10:00:00Z',
    firstTimeWatched: true,
    watchDate: '2024-03-10',
    imageUrl: 'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop',
    tags: ['Epic', 'Visually Stunning', 'Adaptation', 'Space Opera', 'Masterpiece'],
  },
  {
    id: '2',
    type: 'music',
    title: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    album: 'The Dark Side of the Moon',
    year: 1973,
    genre: 'Progressive Rock',
    rating: 5,
    reviewText: 'A timeless exploration of the human condition through sonic innovation. Every track flows seamlessly into the next, creating a cohesive journey through themes of greed, time, death, and mental illness. The production quality remains unmatched even 50 years later, with each listen revealing new layers and details. David Gilmour\'s guitar work is transcendent, particularly on "Time" and "Money."',
    dateReviewed: '2024-03-12T14:30:00Z',
    label: 'Harvest Records',
    duration: '42:59',
    imageUrl: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop',
    tags: ['Classic', 'Progressive', 'Concept Album', 'Timeless', 'Psychedelic'],
  },
  {
    id: '3',
    type: 'cinema',
    title: 'The Godfather',
    director: 'Francis Ford Coppola',
    year: 1972,
    genre: 'Crime Drama',
    rating: 5,
    reviewText: 'Coppola\'s epic tale of power, family, and corruption remains one of cinema\'s greatest achievements. Marlon Brando\'s portrayal of Don Vito Corleone is iconic, while Al Pacino\'s transformation from reluctant son to ruthless don is masterfully executed. The film\'s exploration of the American Dream\'s dark underbelly is both compelling and disturbing.',
    dateReviewed: '2024-03-08T20:15:00Z',
    firstTimeWatched: false,
    watchDate: '2024-03-05',
    imageUrl: 'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop',
    tags: ['Classic', 'Crime', 'Family Saga', 'Iconic', 'American Cinema'],
  },
  {
    id: '4',
    type: 'music',
    title: 'OK Computer',
    artist: 'Radiohead',
    album: 'OK Computer',
    year: 1997,
    genre: 'Alternative Rock',
    rating: 4,
    reviewText: 'Radiohead\'s prescient masterpiece about technology\'s impact on humanity feels more relevant than ever. Thom Yorke\'s paranoid vocals perfectly complement the band\'s experimental soundscapes. "Paranoid Android" and "Karma Police" showcase the band at their creative peak, blending accessibility with avant-garde sensibilities.',
    dateReviewed: '2024-03-05T16:45:00Z',
    label: 'Parlophone',
    duration: '53:21',
    imageUrl: 'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=1920&h=1080&fit=crop',
    tags: ['Alternative', 'Experimental', 'Technology', 'Influential', '90s'],
  }
];